### ISSUE TITLE
error when running hic_exactTest with sparse data

### ISSUE THREAD

**Issue by armenabnousi** [dozmorovlab/multiHiCcompare#1]
Hi, my data is very sparse and I'm getting this error. 
```
hicexp <- hic_exactTest(hicexp, p.method = 'fdr', parallel = FALSE, max.pool = 0.4)
Error in table_by_dist[[i - 1]] : 
  attempt to select less than one element in get1index <real>
```

I have tried setting max.pool to 0 but it still gives me the same error. Do you have any suggestions for that? Thank you!

**Comment by armenabnousi** [comment]
I tried copy-pasting the function definitions from the GitHub and it worked, so I suppose the problem is fixed in newer version. My multiHiCcompare version is 1.0.0

**Comment by jstansfield0** [comment]
I'd recommend reinstalling the newest version from the github repository.
