### ISSUE TITLE
error when running make_hicexp 'long vectors not supported yet'

### ISSUE THREAD

**Issue by hrstu** [dozmorovlab/multiHiCcompare#11]
Hi, Thanks for the great tool. I am running into the below error when I run make_hicexp:

Error: 
`Error in vec_slice(x_out, x_slicer) : 
  long vectors not supported yet: ../../src/include/Rinlinedfuns.h:535`

Command:
`hicexp1 <- make_hicexp(cond1_r1_cis,cond1_r2_cis,cond2_r1_cis,cond2_r2_cis, 
                       groups = c(0,0,1,1), 
                       zero.p = 0.8, A.min = 5, filter = TRUE,
                       remove.regions = hg19_cyto)`

Example input:
`head(cond1_r1_cis)`
chr region1 region2   IF
1.1   1       0 1000000 1066
1.2   1 1000000 2000000  497
1.3   1 2000000 3000000   47
1.4   1 3000000 4000000   19
1.5   1 4000000 5000000   19
1.6   1 5000000 6000000   12

I am starting from hicpro data (the 1000000 binned raw matrix + bed to hicpro2bedpe) and then concatenated all the chromosomes together to generate one data frame for each condition/replicate. Each data frame has around 200,000 rows - is this too many for R to accommodate? I am using R version 4.0.1. I am able to get it to work when using a single chromosome. Let me know if I can provide more context for the issue. Thanks!

**Comment by mdozmorov** [comment]
Hi @hrstu, ees, it is likely the memory issue. I would recommend running multiHiCcompare on one or several chromosomes, not all. I'm now sure which resolution the data is, and which OS, but it's clearly the memory issue. Closing, but ask more if needed.

**Comment by ashishjain1988** [comment]
Hi @mdozmorov I am also facing the same issue while running make_hicexp on whole genome for 18 samples. I am doing it on an HPC so memory is not an issue. I have another question regarding that. Is the patterns (or differential contacts) between the samples changes if we normalized the data based on different subsets of genome (eg. data normalized on chromosome 4 vs whole genome)?

**Comment by mdozmorov** [comment]
We haven't designed multiHiCcompare for whole genome normalization. For two reasons: 1. the inter-chromosomal interactions are much sparser and won't be informative or skew the normalization, and 2. the size of the data would be way more than R can handle. It may not be just memory but also R limitation.

Yes, hypothetically, the data normalized per chromosome will be different from the whole genome normalization. I'd strongly recommend per-chromosome normalization. I believe, we tested multiHiCcompare with 16 samples. It should handle 18 samples because it normalizes two samples at a time.

**Comment by ashishjain1988** [comment]
@mdozmorov Thank you for the information. I have more question regarding the per chromosome normalization. You strongly recommend doing the per chromosome normalization. Will it be correct if we do per chromosome normalization for the samples and then combine all the normalized data for QC (correlation analysis/PCA)?

**Comment by mdozmorov** [comment]
Yes if correlation/PCA are also done on per chromosome basis. That's how I do it, e.g., do correlations between chromosome-specific matrices and then get an average correlation coefficient.

**Comment by ashishjain1988** [comment]
Will it be fine if I concatenate the normalized data for each chromosome and then do PCA (I am not sure how to merge results for PCA for individual chromosome)? In the code, I can see that the normalization is carrying out on each chromosome individually. So will it work if I supply all cis contacts in the hicexp object, do the normalization, and then use the normalized hic_table for downstream analysis (QC/differential contacts)?

**Comment by mdozmorov** [comment]
This is how I do it, get HiCRep correlations for each chromosome, assemble them in a matrix and do MDS on them https://github.com/dozmorovlab/PDXHiC_supplemental/blob/main/Fig4_HiC_misc/02_replicates_HiCrep.Rmd

There are multiple tools for doing PCA on all chromosomes, HiCExplorer, FAN-C, etc.

**Comment by ashishjain1988** [comment]
Thank you!
