### ISSUE TITLE
One versus many

### ISSUE THREAD

**Issue by imerelli** [dozmorovlab/multiHiCcompare#3]
Hi, I have an experiment in which I have a single matrix for one condition and three matrices for the other condition. How can I deal with this situation? Looking at the code, in this case, multihiccompare will use the normal edger estimation of variance, but what will happen for the single matrix?

**Comment by mdozmorov** [comment]
There are two strategies:

1) Merge the three matrices into one, then do one-vs-one comparison.
2) Compare a single matrix vs. each of the three matrices, then look for differential results consistently detected in all three comparisons.

Even the 2nd route is more laborious, I'd recommend going that route.

**Comment by mdozmorov** [comment]
Closed due to inactivity.
