### ISSUE TITLE
calling specific chromosomes

### ISSUE THREAD

**Issue by feefee20** [dozmorovlab/multiHiCcompare#6]
Thanks for multiHiCcompare. Since I got a memory error when trying it at low resolution (10K), I am trying to run it with some sequential numbers of chromosome (e.g. chr 5:10). As shown below, chromosome names were defined as chr5 to chr8 and I expected to call the information of specific chromosome.

```
chr <-paste0('chr',c(5:8))# Chromosome names 
samples <-paste0('NONE25k_gr',c(1,2,3,4)) # Sample names 
res <- 10000 # Data resolution

# Read data
sample_list <-list() 
chr_list <-list()
for(j in 1:length(samples)) {
  for (i in 1:length(chr))) {                         
    chr_list[[i]] <-read_tsv(paste0(samples[j],"/",
                                    samples[j],
                                    ".", chr[i],".", res,".txt"),
                             col_names = FALSE) %>% as.data.table()
    # Add column indicating the chromosome 
    chr_list[[i]] <-cbind(i, chr_list[[i]])
    colnames(chr_list[[i]]) <-c('chr','region1',
                                 'region2','IF')
  }
  sample_list[[j]] <- chr_list 
  chr_list <-list()
}
```

Here's the results called by the commands. The right information from chr5 to chr9 is likely called but wrong sequential numbers (chr1 to chr4) are assigned to the called information (e.g. chr1 is not real chr1, actually chr5). Any ideas to get right numbers for specific chromosomes (e.g. chr5 to chr8)? Thanks!

> sample_list <-lapply(sample_list, rbindlist)
> sample_list[[1]]
         chr  region1  region2  IF
      1:   1   130000   130000  12
      2:   1   110000   140000   2
      3:   1   130000   140000  38
      4:   1   140000   140000 692
      5:   1   130000   150000   9
     ---                          
8775887:   4 64280000 64330000   1
8775888:   4 64300000 64330000   1
8775889:   4 64310000 64330000   6
8775890:   4 64320000 64330000  16
8775891:   4 64330000 64330000  23

**Comment by mdozmorov** [comment]
Your `i` variable goes from 1 to 4. When you use it within the `".", chr[i],".", res,".txt"` code, it correctly refers to the chromosome you defined above. When you do `cbind(i, chr_list[[i]])`, 1, 2, 3, 4 will be used. You need to redefine your variables. As a fragile hack, you know that chromosome counts are offset by 4 from the 1,2,3,4 counts, so you can use `chr_list[[i]] <-cbind(i + 4, chr_list[[i]])`
